pages = [{"l":"index.html#","e":false,"i":"","n":"mat","t":"mat","d":"","k":"static","x":""},
{"l":"me/cytrowski/mat.html#","e":false,"i":"","n":"me.cytrowski.mat","t":"me.cytrowski.mat","d":"","k":"package","x":""},
{"l":"me/cytrowski/mat.html#materialize-fffff7c4","e":false,"i":"","n":"materialize","t":"materialize[A]: Any","d":"me.cytrowski.mat","k":"def","x":""},
{"l":"me/cytrowski/mat.html#materializeOpt-fffff7c4","e":false,"i":"","n":"materializeOpt","t":"materializeOpt[A]: Any","d":"me.cytrowski.mat","k":"def","x":""},
{"l":"me/cytrowski/mat/Materialize$.html#","e":false,"i":"","n":"Materialize","t":"Materialize","d":"me.cytrowski.mat","k":"object","x":""},
{"l":"me/cytrowski/mat/Materialize$.html#Aux-0","e":false,"i":"","n":"Aux","t":"Aux[A, O <: A] = Materialize[A] { type Out = O;  }","d":"me.cytrowski.mat.Materialize","k":"type","x":""},
{"l":"me/cytrowski/mat/Materialize$.html#apply-51","e":false,"i":"","n":"apply","t":"apply[A](using materialize: Materialize[A]): Materialize[A]","d":"me.cytrowski.mat.Materialize","k":"def","x":""},
{"l":"me/cytrowski/mat/Materialize$.html#derived-fffffc41","e":false,"i":"","n":"derived","t":"derived: [A] => Materialize[A]","d":"me.cytrowski.mat.Materialize","k":"given","x":""},
{"l":"me/cytrowski/mat/Materialize$.html#fromValue-fffff0ae","e":false,"i":"","n":"fromValue","t":"fromValue[A, O <: A](value: => O): Aux[A, O]","d":"me.cytrowski.mat.Materialize","k":"def","x":""},
{"l":"me/cytrowski/mat/Materialize.html#","e":false,"i":"","n":"Materialize","t":"Materialize[A]","d":"me.cytrowski.mat","k":"trait","x":""},
{"l":"me/cytrowski/mat/Materialize.html#Out-0","e":false,"i":"","n":"Out","t":"Out <: A","d":"me.cytrowski.mat.Materialize","k":"type","x":""},
{"l":"me/cytrowski/mat/Materialize.html#apply-993","e":false,"i":"","n":"apply","t":"apply(): Out","d":"me.cytrowski.mat.Materialize","k":"def","x":""}];