name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test supported Scala versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: corretto
          # renovate: datasource=java-version depName=java-jdk
          java-version: 25

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**', '.scalafmt.conf') }}

      - name: Check formatting
        run: sbt --batch scalafmtCheckAll

      - name: Run tests
        run: sbt --batch +testFull

      - name: Coverage
        run: |
          sbt --batch ';++3.8.4;coverage;testFull;coverageReport'

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: target/out/jvm/scala-3.8.4/mat/coverage-report
          if-no-files-found: error

      - name: Package
        run: sbt --batch +package
